### ISSUE TITLE
KJB Talking over Characters talking

### ISSUE THREAD

**Issue by flyingpianos** [IBwWG/mathildagame-bugs#105] opened 2016-09-05 05:30 UTC
It seemed to be happening at the opening of each game wherever there was immediate verbage at the start, so I'm reporting it.  But I don't remember exactly which ones it happened on (sorry, Kev!)...
When you select a game, it opens, and where Willy or Mathilda are saying something right at the start, it is simultaneous with Kev saying something about pressing "Pause".  Since they are both talking at the same time, I missed what both were saying...

**Comment by IBwWG** [comment] 2016-09-05 12:48
Thanks, I will look into this!  I hadn't noticed it as of the last check, but maybe it's a regression.

**Comment by IBwWG** [comment] 2016-09-05 14:48
I tried on a fresh save, and I only hear my announcer voice, the others should pause until you unpause the game.

Was it on a fresh save / new game?  Is it the help thing that makes the buttons at the top flash red while it talks about them?  Have you been able to reproduce it other times?

When you say at the opening of each game, this speech that flashes the buttons, it should only happen on the very first game you play on a brand new save.  If it happens on subsequent games that's a separate bug in itself.  Can you confirm that one too?  I'm not seeing either of these, it's just based on your description.

**Comment by IBwWG** [comment] 2016-09-05 14:49
Also did you happen to hit Skip or something?  Did you notice anything else weird, e.g. no music once you unpaused?

**Comment by IBwWG** [comment] 2016-09-06 09:56
I couldn't confirm this also on the latest 0.95 release.  Would you mind trying it again with that one?

**Comment by IBwWG** [comment] 2016-09-07 07:47
Actually, if it _is_ music-related (a music file not playing may throw off the normal timing of the game) due to that glitch you were experiencing earlier with ogg files...that should be fixed in the bleeding edge build I'm about to put out.  If you update your itch.io app itself, the latest version of the app will let you pick between updating using the bleeding edge channel or the normal one, but you may need to first uninstall the game and install it again, before it gives you the choice.

**Comment by IBwWG** [comment] 2016-09-07 09:50
Bleeding edge is up now.

**Comment by IBwWG** [comment] 2016-09-10 09:48
Please reopen if it occurs on the latest update (1.0.1 as of this writing.)

**Closed as completed by IBwWG** 2016-09-10 09:48 UTC
Labels: pause/help subscreen
